project:
  type: website

website:
  title: "Platform Demo"
  navbar:
    background: secondary
    left:
      - text: "Home"
        href: index.qmd
      - text: "Case Studies"
        href: docs/case-studies/index.qmd
      - text: "Explainers"
        href: docs/explainers/index.qmd
      - text: "Training"
        href: docs/training/index.qmd
      - text: "Advice"
        href: docs/advice/index.qmd 
    right:
      - href: https://github.com/
        icon: github
      - href: https://stackoverflow.com/
        icon: stack-overflow
      - href: https://twitter.com/
        icon: twitter
    pinned: false

  sidebar: 
    - id: case-studies
      title: "Case Studies"
      style: "floating"
      collapse-level: 2
      align: left
      contents:
        - docs/case-studies/index.qmd
        - href: docs/case-studies/business-and-industry/index.qmd
          text: "Business & Industry"
        - href: docs/case-studies/social-and-public-policy/index.qmd
          text: "Social & Public Policy"
        - href: docs/case-studies/science-and-academia/index.qmd
          text: "Science & Academia"

    - id: explainers
      title: "Explainers"
      style: "floating"
      collapse-level: 2
      align: left
      contents:
        - docs/explainers/index.qmd
        - href: docs/explainers/tools/index.qmd
          text: "Tools"
        - href: docs/explainers/methods/index.qmd
          text: "Methods"
        - href: docs/explainers/ideas/index.qmd
          text: "Ideas & Concepts"

    - id: training
      title: "Training"
      style: "floating"
      collapse-level: 2
      align: left
      contents:
        - docs/training/index.qmd
        - href: docs/training/exercises/index.qmd
          text: "Exercises"
        - href: docs/training/guides/index.qmd
          text: "Guides"
        - href: docs/training/recommended-reading/index.qmd
          text: "Recommended Reading"
        - href: docs/training/datasets/index.qmd
          text: "Datasets"

    - id: advice
      title: "Advice"
      style: "floating"
      collapse-level: 2
      align: left
      contents:
        - docs/advice/index.qmd
        - href: docs/advice/helpline/index.qmd
          text: "The Helpline"
        - href: docs/advice/career-profiles/index.qmd
          text: "Career Profiles"
        - href: docs/advice/professional-development/index.qmd
          text: "Professional Development"
        - href: docs/advice/ethics-bestpractice/index.qmd
          text: Ethics & Best Practice

  page-footer: 
    left: "Copyright 2022, Brian Tarran"
    center:
      - docs/about.qmd  
    right: 
      - href: https://github.com/
        icon: github
      - href: https://stackoverflow.com/
        icon: stack-overflow
      - href: https://twitter.com/
        icon: twitter

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

freeze: auto